text_generator/__init__.py
from flask import Flask
from .routes import generator

def create_app(config_file='settings.py'):

    # __name__ is global variable, here would be generator.py
    # front end on Flask is using a templating engine, static files (images, videos)
    # need to specify a static path within flask, where our files will live
    app = Flask(__name__, static_url_path="/tmp", static_folder="tmp")

    # configure our app. pass in config_file which has out settings
    app.config.from_pyfile(config_file)

    # register our blueprint
    #routes file will contain routes we will hit, and contains our blueprint
    # gives organization to our entire application
    # call our blueprint generator
    app.register_blueprint(generator)
    return app

text_generator/routes.py
from flask import Blueprint, render_template, request, redirect
from .generator import ai #will have class AI in generator.py which instantiates an object called ai
import re

# Flask uses concept of Blueprint for making application components,
# and supporting common patterns within app or accross apps
# can greatly simplify how large applications work
generator = Blueprint('generator', __name__)

@generator.route('/')
def index():
    return render_template('index.html', parameter="") #will search inside of templates folder and return correct file we require
    # can access parameter inside of html file
    # can do opposite, put parameter = request.form('parameter') inside our index function to have html access stuff from this file

@generator.route('/analyze', methods=['POST'])
def analyze():
    ctx = request.form['context']
    #ctx = request.form['context']
    qst = request.form['question']
    ans = '[ANSWER]:'
    prefix = '<|startoftext|>\n[CONTEXT]: ' + ctx + '\n[QUESTION]:' + qst + '\n' + ans #+ "\'"
    text = ai.generate_text(prefix)
    text = re.sub('[!\'\]\[\,]', '', text) #getting rid of any extra symbols
    print("Please wait...")

    return render_template('index.html', text=text) #text is response that ai generates

text_generator/templates/index.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<div style="display: flex; flex-direction: row; width: 100%; height: 100%; background-color: rgb(210, 173, 173);">
  <div>
    <form style="max-width: 1000px; margin: 50px; justify-self: center;" method="POST" action="{{ url_for('generator.analyze') }}">
      <div class="form-group">
        <label for="context" style="font-size: 33px;">Context</label>
        <input type="text" style="height: 100px; font-size: 20px;" class="form-control" placeholder="Enter Text" name="context"/>
      </div>
      <div class="form-group">
        <label for="question" style="font-size: 33px;">Question</label>
        <input type="text" style="height: 60px; font-size: 20px;" class="form-control" placeholder="Enter Text" name="question"/>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <p class="text-left" style="cursor: pointer; margin: 50px; padding: 15px; border-radius: 12px; font-size: 18px; background-color: rgb(154, 155, 199); max-width: 1000px;">
      OpenAI: {{ text }}
    </p>
  </div>
  <div>
    <img style="margin: 50px; border: 0;" alt="OPENAI" width="800" height="650" src="/tmp/openai.jpeg" />
  </div>
</div>